// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxrVI5g9HBSyaks3tELy3d4C08WKGFlaM',
    appId: '1:741794298657:web:454162d5085b6784fb9c60',
    messagingSenderId: '741794298657',
    projectId: 'url-sca',
    authDomain: 'url-sca.firebaseapp.com',
    storageBucket: 'url-sca.appspot.com',
    measurementId: 'G-B60PLVZ3TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnh2F5eoUG6JOR-bKpwwj7OLs8yi2JADk',
    appId: '1:741794298657:android:a04517a77ae42168fb9c60',
    messagingSenderId: '741794298657',
    projectId: 'url-sca',
    storageBucket: 'url-sca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr84rPf9H66DCOEZWCf8q6robo8fVTjlU',
    appId: '1:741794298657:ios:192521e9066d3adcfb9c60',
    messagingSenderId: '741794298657',
    projectId: 'url-sca',
    storageBucket: 'url-sca.appspot.com',
    iosClientId: '741794298657-4uoh51oo1p0e8k80hgcfqidepf0rhin1.apps.googleusercontent.com',
    iosBundleId: 'com.example.urlScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr84rPf9H66DCOEZWCf8q6robo8fVTjlU',
    appId: '1:741794298657:ios:192521e9066d3adcfb9c60',
    messagingSenderId: '741794298657',
    projectId: 'url-sca',
    storageBucket: 'url-sca.appspot.com',
    iosClientId: '741794298657-4uoh51oo1p0e8k80hgcfqidepf0rhin1.apps.googleusercontent.com',
    iosBundleId: 'com.example.urlScan',
  );
}
